config/routes.rb
Rails.application.routes.draw do
  
resources :audios
root :to => "empresas#index"
resources :empresas do
  resources :ubicacion_geos do
    collection do
        get 'mapComplet'
    end
  end
  resources :estadisticas
  resources :noticia_empresas
  resources :videos
  resources :consulta_clientes
  resources :productos do
    resources :galeria_procesos
    resources :preparar_mates
    resources :galeria_prep_mates
    resources :prop_generals do
      resources :prop_general_items
      resources :galeria_props
    end
    resources :item_productos do
       resources :galeria_imagenes
       resources :videos_productos
       resources :opinions
       resources :detalles do
          resources :prop_especificas
       end
    end
  end
  resources :informacion_empresas do
    resources :item_de_infos
  end
end

end

app/models/informacion_empresa.rb
class InformacionEmpresa < ActiveRecord::Base
  belongs_to :empresa
  has_many :item_de_infos, dependent: :destroy
end

app/controllers/informacion_empresas_controller.rb
class InformacionEmpresasController < ApplicationController
 

  # GET /informacion_empresas
  # GET /informacion_empresas.json
  def index
    @empresa = Empresa.find(params[:empresa_id])
    @informacion_empresas = @empresa.informacion_empresas
  end

  # GET /informacion_empresas/1
  # GET /informacion_empresas/1.json
  def show
    @empresa = Empresa.find(params[:empresa_id])
    @informacion_empresa = @empresa.informacion_empresas.find(params[:id])
  end

  # GET /informacion_empresas/new
  def new
 #   @informacion_empresa = InformacionEmpresa.new
    @empresa = Empresa.find(params[:empresa_id])
    @informacion_empresa = @empresa.informacion_empresas.new
  end

  # GET /informacion_empresas/1/edit
  def edit
     @empresa = Empresa.find(params[:empresa_id])
     @informacion_empresa = @empresa.informacion_empresas.find(params[:id])
  end

  # POST /informacion_empresas
  # POST /informacion_empresas.json
  def create
    #@informacion_empresa = InformacionEmpresa.new(informacion_empresa_params)
  @empresa = Empresa.find(params[:empresa_id])
  @informacion_empresa = @empresa.informacion_empresas.create(informacion_empresa_params)
    respond_to do |format|
      if @informacion_empresa.save
        format.html { redirect_to empresa_informacion_empresas_path, notice: 'Informacion empresa was successfully created.' }
        format.json { render :show, status: :created, location: @informacion_empresa }
      else
        format.html { render :new }
        format.json { render json: @informacion_empresa.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /informacion_empresas/1
  # PATCH/PUT /informacion_empresas/1.json
  def update
    @empresa = Empresa.find(params[:empresa_id])
    @informacion_empresa = @empresa.informacion_empresas.find(params[:id])
    respond_to do |format|
      if @informacion_empresa.update(informacion_empresa_params)
        format.html { redirect_to empresa_informacion_empresas_path, notice: 'Informacion empresa was successfully updated.' }
        format.json { render :show, status: :ok, location: @informacion_empresa }
      else
        format.html { render :edit }
        format.json { render json: @informacion_empresa.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /informacion_empresas/1
  # DELETE /informacion_empresas/1.json
  def destroy
    @empresa = Empresa.find(params[:empresa_id])
    @informacion_empresa = @empresa.informacion_empresas.find(params[:id])
    @informacion_empresa.destroy
    respond_to do |format|
      format.html { redirect_to empresa_informacion_empresas_path, notice: 'Informacion empresa was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.


    # Never trust parameters from the scary internet, only allow the white list through.
    def informacion_empresa_params
      params.require(:informacion_empresa).permit(:itemTitulo)
    end
end

app/helpers/informacion_empresas_helper.rb
module InformacionEmpresasHelper
end

app/views/informacion_empresas/_form.html.erb
<%= form_for ([@empresa, @informacion_empresa])  do |f| %>

  <% if @informacion_empresa.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@informacion_empresa.errors.count, "error") %> prohibited this informacion_empresa from being saved:</h2>

      <ul>
      <% @informacion_empresa.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <form class="form-horizontal" >
      <fieldset>
        <legend><h3>Datos de Noticias</h3></legend>
          <div class="form-group">
            <label for="" class="col-lg-4 control-label">Título de Item:</label>
            <div class="col-lg-12">
              <%= f.text_field :itemTitulo, class: "form-control", placeholder: "Título"%>
            </div>
          </div>
          <div class="form-group">
              <div class="col-lg-12 text-center">
                  <%= f.submit "Guardar", class: "btn btn-info btn-raised" %>
                  <%= link_to 'Volver', empresa_informacion_empresas_path,class: "btn btn-info btn-raised" %>
              </div>
          </div>
      <% end %>
      </fieldset>
  </form>

app/views/informacion_empresas/edit.html.erb
<div class="container">
    <div class="col-lg-7 col-lg-offset-2">
        <div class="panel panel-info">
            <div class="panel-heading">
                <h2 class="panel-title text-center">Contenido de Item</h2>
            </div>
                
            <div class="panel-body">
				<%= render 'form' %>
			</div>
		</div>
	</div>
</div>

app/views/informacion_empresas/index.html.erb
<div class="container">
  <div class="row">
  <div class="col-md-8 col-lg-offset-2">
      <div class="panel panel-info">
        <div class="panel-heading">
          <h2 class="panel-title text-center" >Información de Empresa</h2>
        </div>
        <div class="col-lg-offset-5">
          <div class="btn-group">
            <a ><%= link_to "<button type='button'class='btn btn-info'>Nuevo</button>".html_safe, new_empresa_informacion_empresa_path%></a>   
          </div> 
          <div class="btn-group">
            <a ><%= link_to "<button type='button'class='btn btn-info'>Volver</button>".html_safe, empresa_path(@empresa)%></a>   
          </div> 
        </div>                      
        <div class="panel-body">
          <table class="table table-striped "> 
            <thead>
              <tr class="info">
               <th class="text-center"><h5><b>Titulo de item</b></h5></th>
               <th class="text-center"><h5><b>Acciones</b></h5></th>
             </tr>
           </thead>
           <% if @empresa.informacion_empresas.empty? == false %>
           <% @informacion_empresas.each do |informacion_empresa| %>
           <div class="row">
            <tr class="active">
              <td ><h5><%= informacion_empresa.itemTitulo %></h5></td>
              <td class="text-center">
                <div class="col-lg-offset2">
                  <div class="btn-group">
                    <a><%= link_to 'Contenidos de Item',empresa_informacion_empresa_item_de_infos_path(@empresa,informacion_empresa) ,:class => "btn btn-info" %></a>                                
                    <a><%= link_to 'Editar', [:edit, @empresa,informacion_empresa],:class => "btn btn-info"%></a>
                    <a><%= link_to 'Eliminar',[informacion_empresa.empresa, informacion_empresa], method: :delete, data: { confirm: 'Are you sure?' },:class => "btn btn-info" %></a>
                  </div>
                </div>                          
              </td>               
            </tr>   
          </div>
          <% end %>
          <% end %>
        </table>             
      </div>      
    </div>
  </div>
</div>
</div>

app/views/informacion_empresas/new.html.erb
<div class="container">
    <div class="col-lg-7 col-lg-offset-2">
        <div class="panel panel-info">
            <div class="panel-heading">
                <h2 class="panel-title text-center">Contenido de Item</h2>
            </div>
                
            <div class="panel-body">
				<%= render 'form' %>
			</div>
		</div>
	</div>
</div>

app/views/informacion_empresas/show.html.erb
<%= form_for([@empresa, @informacion_empresa]) do |f| %>

<p id="notice"><%= notice %></p>

<p>
  <strong>Itemtitulo:</strong>
  <%= @informacion_empresa.itemTitulo %>
</p>

<p>
  <strong>Empresa:</strong>
  <%= @informacion_empresa.empresa.nombre %>
</p>

<%= link_to 'Edit', edit_empresa_informacion_empresa_path(@empresa,@informacion_empresa) %> |
<%= link_to 'Back', empresa_informacion_empresas_path %>
<% end %>