config/routes.rb
Rails.application.routes.draw do
  
resources :audios
root :to => "empresas#index"
resources :empresas do
  resources :ubicacion_geos do
    collection do
        get 'mapComplet'
    end
  end
  resources :estadisticas
  resources :noticia_empresas
  resources :videos
  resources :consulta_clientes
  resources :productos do
    resources :galeria_procesos
    resources :preparar_mates
    resources :galeria_prep_mates
    resources :prop_generals do
      resources :prop_general_items
      resources :galeria_props
    end
    resources :item_productos do
       resources :galeria_imagenes
       resources :videos_productos
       resources :opinions
       resources :detalles do
          resources :prop_especificas
       end
    end
  end
  resources :informacion_empresas do
    resources :item_de_infos
  end
end

end

app/models/audio.rb
class Audio < ActiveRecord::Base

	has_attached_file :image, :styles => {:small => "100*100"}
	validates_attachment_presence :image
	validates_attachment_content_type :image, :content_type => [ 'image/png','image/jpeg','image/jpeg']

	has_attached_file :document
	validates_attachment_presence :document
	validates_attachment_content_type :document, :content_type => [ 'application/pdf','text/plain']

	has_attached_file :audio
	validates_attachment_presence :audio
	validates_attachment_content_type :audio, :content_type => [ 'audio/mp3','audio/mpeg']

end

app/models/detalle.rb
class Detalle < ActiveRecord::Base
	belongs_to :item_producto
	has_many :prop_especificas
end

app/models/empresa.rb
class Empresa < ActiveRecord::Base
	has_many :informacion_empresas, dependent: :destroy
	has_many :noticia_empresas, dependent: :destroy
    has_many :productos, dependent: :destroy
    has_many :ubicacion_geos, dependent: :destroy
    has_many :videos, dependent: :destroy
    has_many :consulta_clientes, dependent: :destroy
 	has_many :estadisticas, dependent: :destroy

 	has_attached_file :image, :styles => { :medium => "90x90>", :thumb => "90x90>" }
    validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

   def image_url
     image.url(:thumb)
   end
end

app/models/estadistica.rb
class Estadistica < ActiveRecord::Base
	  belongs_to :empresa
end

app/models/galeria_imagene.rb
class GaleriaImagene < ActiveRecord::Base
  belongs_to :item_producto
  has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "300x300>" }
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

   def image_url
     image.url(:thumb)
   end
end

app/models/galeria_proceso.rb
class GaleriaProceso < ActiveRecord::Base
  belongs_to :producto
  has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "300x300>" }
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

   def image_url
     image.url(:thumb)
   end
end

app/models/galeria_prop.rb
class GaleriaProp < ActiveRecord::Base
  belongs_to :prop_general
  has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "300x300>" }
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

   def image_url
     image.url(:thumb)
   end
end

app/models/item_de_info.rb
class ItemDeInfo < ActiveRecord::Base
  belongs_to :informacion_empresa
  has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "300x300>" }
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
   def image_url
     image.url(:thumb)
   end
end

app/models/item_producto.rb
class ItemProducto < ActiveRecord::Base
  belongs_to :producto
  has_many :galeria_imagenes
  has_many :videos_productos
  has_many :opinions
  has_many :detalles
  has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "300x300>" }
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
  def image_url
     image.url(:thumb)
  end
end

app/models/noticia_empresa.rb
class NoticiaEmpresa < ActiveRecord::Base
  belongs_to :empresa
  has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "300x300>" }
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

   def image_url
     image.url(:thumb)
   end
end

app/models/opinion.rb
class Opinion < ActiveRecord::Base
	belongs_to :item_producto
end

app/models/preparar_mate.rb
class PrepararMate < ActiveRecord::Base
	belongs_to :producto
	
end

app/models/producto.rb
class Producto < ActiveRecord::Base
  belongs_to :empresa
  has_many :item_productos, dependent: :destroy
  has_many :prop_generals, dependent: :destroy
  has_many :galeria_procesos, dependent: :destroy
  has_many :preparar_mates, dependent: :destroy
  has_many :galeria_prep_mates, dependent: :destroy
end

app/models/prop_especifica.rb
class PropEspecifica < ActiveRecord::Base
	belongs_to :detalle
end

app/models/prop_general.rb
class PropGeneral < ActiveRecord::Base
	belongs_to :producto
	has_many :prop_general_items, dependent: :destroy
	has_many :galeria_props, dependent: :destroy
end

app/models/ubicacion_geo.rb
class UbicacionGeo < ActiveRecord::Base
  belongs_to :empresa
  geocoded_by :address
  after_validation :geocode
  
  has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "300x300>" }
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
  def image_url
     image.url(:thumb)
  end

end

app/models/video.rb
class Video < ActiveRecord::Base
	  belongs_to :empresa
      
end

app/models/videos_producto.rb
class VideosProducto < ActiveRecord::Base
	belongs_to :item_producto
end

app/controllers/noticia_empresas_controller.rb
class NoticiaEmpresasController < ApplicationController


  # GET /noticia
  # GET /noticia.json
  def index
    @empresa = Empresa.find(params[:empresa_id])
    @noticia_empresas = @empresa.noticia_empresas
  end

  # GET /noticia/1
  # GET /noticia/1.json
  def show
    @empresa = Empresa.find(params[:empresa_id])
    @noticia_empresa = @empresa.noticia_empresas.find(params[:id])
  end

  # GET /noticia/new
  def new
    @empresa = Empresa.find(params[:empresa_id])
    @noticia_empresa = @empresa.noticia_empresas.new
  end

  # GET /noticia/1/edit
  def edit
     @empresa = Empresa.find(params[:empresa_id])
     @noticia_empresa = @empresa.noticia_empresas.find(params[:id])
  end

  # POST /noticia
  # POST /noticia.json
  def create
  @empresa = Empresa.find(params[:empresa_id])
  @noticia_empresa = @empresa.noticia_empresas.create(noticia_empresa_params)
    respond_to do |format|
      if @noticia_empresa.save
        format.html { redirect_to empresa_noticia_empresas_path(@empresa,@noticia_empresa), notice: 'Noticium was successfully created.' }
        format.json { render :show, status: :created, location: @noticia_empresa }
      else
        format.html { render :new }
        format.json { render json: @noticia_empresa.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /noticia/1
  # PATCH/PUT /noticia/1.json
  def update
    @empresa = Empresa.find(params[:empresa_id])
    @noticia_empresa = @empresa.noticia_empresas.find(params[:id])
    respond_to do |format|
      if @noticia_empresa.update(noticia_empresa_params)
        format.html { redirect_to empresa_noticia_empresas_path(@empresa,@noticia_empresa), notice: 'Noticium was successfully updated.' }
        format.json { render :show, status: :ok, location: @noticia_empresa }
      else
        format.html { render :edit }
        format.json { render json: @noticia_empresa.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /noticia/1
  # DELETE /noticia/1.json
  def destroy
    @empresa = Empresa.find(params[:empresa_id])
    @noticia_empresa = @empresa.noticia_empresas.find(params[:id])
    @noticia_empresa.destroy
    respond_to do |format|
      format.html { redirect_to empresa_noticia_empresas_path(@empresa,@noticia_empresa), notice: 'Noticium was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def noticia_empresa_params
      params.require(:noticia_empresa).permit(:titulo, :descripcion,:image, :empresa_id)
    end
end

app/helpers/audios_helper.rb
module AudiosHelper
end

app/helpers/detalles_helper.rb
module DetallesHelper
end

app/helpers/noticia_empresas_helper.rb
module NoticiaEmpresasHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/noticia_empresas/_form.html.erb
<%= form_for ([@empresa,@noticia_empresa])  do |f| %>
  <% if @noticia_empresa.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@noticia_empresa.errors.count, "error") %> prohibited this noticium from being saved:</h2>

      <ul>
      <% @noticia_empresa.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <form class="form-horizontal" >
      <fieldset>
        <legend><h3>Datos de Noticias</h3></legend>
          <div class="form-group">
          <label for="" class="col-lg-2 control-label">Titulo:</label>
             <!-- <%= f.label :titulo, class: "col-lg-2 control-label"  %>-->
            <div class="col-lg-10">
              <%= f.text_field :titulo, class: "form-control", placeholder: "Título"%>
            </div>
          </div>
          <div class="form-group">
              <label for="" class="col-lg-2 control-label">Descripción:</label>
            <div class="col-lg-10">
              <%= f.text_area :descripcion, class: "form-control", placeholder: "Descripción"%>
            </div>
          </div>
          <div class="form-group">
              <label for="" class="col-lg-2 control-label">Imagen:</label>
            <div class="col-lg-10">
              <%= f.file_field :image, class: "form-control"%>
            </div>
          </div>
       <div class="col-lg-offset-4">
              <div class="btn-group">
                  <%= f.submit "Guardar", class: "btn btn-info btn-raised" %>
              </div>
              <div class="btn-group">
                  <%= link_to 'Atrás', empresa_noticia_empresas_path,class: "btn btn-info btn-raised" %>
              </div>
          </div>
      <% end %>
      </fieldset>
  </form>

app/views/noticia_empresas/edit.html.erb
<div class="container">
    <div class="row">
        <div class="col-lg-7 col-lg-offset-3">
            <div class="panel panel-info">
                <div class="panel-heading">
                    <h2 class="panel-title text-center">Editar noticia</h2>
                </div>
                    
                <div class="panel-body">
    				<%= render 'form' %>
    			</div>
    		</div>
    	</div>
    </div>
</div>

app/views/noticia_empresas/index.html.erb
<div class="container">
    <div class="center-block">
        <div class="panel panel-info">
            <div class="panel-heading">
                <h2 class="panel-title text-center" >Gestor de Noticias</h2>
            </div>
            <div class="col-md-3 col-lg-offset-5">
                <div class="btn-group">
                    <a ><%= link_to "<button type='button'class='btn btn-info'>Nuevo</button>".html_safe, new_empresa_noticia_empresa_path %></a> 
                </div>
                <div class="btn-group">
                    <a ><%= link_to "<button type='button'class='btn btn-info'>Volver</button>".html_safe, empresa_path(@empresa)%></a>  
                </div>
            </div>
            <div class="panel-body">
                <table class="table table-striped"> 
                    <thead>                              
                        <tr class="info">
                           <th class="text-center"><h5><b>Titulo</b></h5></th>
                           <th class="text-center"><h5><b>Descripcion</b></h5></th>
                           <th class="text-center"><h5><b>Imagen</b></h5></th>
                           <th class="text-center"><h5><b>Acciones</b></h5></th>
                        </tr>
                    </thead>
                <% if @empresa.noticia_empresas.empty? == false %>
                    <% @noticia_empresas.each do |noticia_empresa| %>
                        <div class="row">
                            <tr class="active">
                                <td class="text-center"><h5><%= noticia_empresa.titulo %></h5></td>
                                <td><h5><%= noticia_empresa.descripcion %></h5></td>
                                <td class="text-center"><h5><%= image_tag noticia_empresa.image.url(:thumb) %></h5></td>
                                <td class="text-center">
                                    <div class="btn-group-vertical">
                                        <!--<a><%= link_to 'Show', empresa_noticia_empresa_path(@empresa,noticia_empresa), :class => "btn btn-info btn-raised"%></a>-->
                                        <a><%= link_to 'Editar', edit_empresa_noticia_empresa_path(@empresa,noticia_empresa),:class => "btn btn-info btn-raised"%></a>
                                        <a><%= link_to 'Eliminar',[noticia_empresa.empresa, noticia_empresa], method: :delete, data: { confirm: 'Are you sure?' },:class => "btn btn-info btn-raised" %></a>
                                    </div>
                                </td>
                            </tr>
                        </div>
                    <%end%>
                <% end %>
                </table>   
            </div>                     
        </div>
    </div>
</div>        

app/views/noticia_empresas/new.html.erb
<div class="container">
    <div class="row">
        <div class="col-lg-7 col-lg-offset-3">
            <div class="panel panel-info">
                <div class="panel-heading">
                    <h2 class="panel-title text-center">Nueva noticia</h2>
                </div>
                    
                <div class="panel-body">
    				<%= render 'form' %>
    			</div>
    		</div>
    	</div>
    </div>
</div>

app/views/noticia_empresas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Titulo:</strong>
  <%= @noticia_empresa.titulo %>
</p>

<p>
  <strong>Descripcion:</strong>
  <%= @noticia_empresa.descripcion %>
</p>
<p>
  <strong>Imagen:</strong>
  <td><%= image_tag @noticia_empresa.image.url(:thumb) %></td>
</p>
<p>
  <strong>Empresa:</strong>
  <%= @noticia_empresa.empresa %>
</p>

<%= link_to 'Edit', edit_empresa_noticia_empresa_path(@empresa,@noticia_empresa) %> |
<%= link_to 'Back',  empresa_noticia_empresas_path %>