config/routes.rb
Rails.application.routes.draw do
  
resources :audios
root :to => "empresas#index"
resources :empresas do
  resources :ubicacion_geos do
    collection do
        get 'mapComplet'
    end
  end
  resources :estadisticas
  resources :noticia_empresas
  resources :videos
  resources :consulta_clientes
  resources :productos do
    resources :galeria_procesos
    resources :preparar_mates
    resources :galeria_prep_mates
    resources :prop_generals do
      resources :prop_general_items
      resources :galeria_props
    end
    resources :item_productos do
       resources :galeria_imagenes
       resources :videos_productos
       resources :opinions
       resources :detalles do
          resources :prop_especificas
       end
    end
  end
  resources :informacion_empresas do
    resources :item_de_infos
  end
end

end

app/models/audio.rb
class Audio < ActiveRecord::Base

	has_attached_file :image, :styles => {:small => "100*100"}
	validates_attachment_presence :image
	validates_attachment_content_type :image, :content_type => [ 'image/png','image/jpeg','image/jpeg']

	has_attached_file :document
	validates_attachment_presence :document
	validates_attachment_content_type :document, :content_type => [ 'application/pdf','text/plain']

	has_attached_file :audio
	validates_attachment_presence :audio
	validates_attachment_content_type :audio, :content_type => [ 'audio/mp3','audio/mpeg']

end

app/models/detalle.rb
class Detalle < ActiveRecord::Base
	belongs_to :item_producto
	has_many :prop_especificas
end

app/models/empresa.rb
class Empresa < ActiveRecord::Base
	has_many :informacion_empresas, dependent: :destroy
	has_many :noticia_empresas, dependent: :destroy
    has_many :productos, dependent: :destroy
    has_many :ubicacion_geos, dependent: :destroy
    has_many :videos, dependent: :destroy
    has_many :consulta_clientes, dependent: :destroy
 	has_many :estadisticas, dependent: :destroy

 	has_attached_file :image, :styles => { :medium => "90x90>", :thumb => "90x90>" }
    validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

   def image_url
     image.url(:thumb)
   end
end

app/models/estadistica.rb
class Estadistica < ActiveRecord::Base
	  belongs_to :empresa
end

app/models/galeria_imagene.rb
class GaleriaImagene < ActiveRecord::Base
  belongs_to :item_producto
  has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "300x300>" }
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

   def image_url
     image.url(:thumb)
   end
end

app/models/galeria_proceso.rb
class GaleriaProceso < ActiveRecord::Base
  belongs_to :producto
  has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "300x300>" }
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

   def image_url
     image.url(:thumb)
   end
end

app/models/galeria_prop.rb
class GaleriaProp < ActiveRecord::Base
  belongs_to :prop_general
  has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "300x300>" }
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

   def image_url
     image.url(:thumb)
   end
end

app/models/item_de_info.rb
class ItemDeInfo < ActiveRecord::Base
  belongs_to :informacion_empresa
  has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "300x300>" }
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
   def image_url
     image.url(:thumb)
   end
end

app/models/item_producto.rb
class ItemProducto < ActiveRecord::Base
  belongs_to :producto
  has_many :galeria_imagenes
  has_many :videos_productos
  has_many :opinions
  has_many :detalles
  has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "300x300>" }
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
  def image_url
     image.url(:thumb)
  end
end

app/models/noticia_empresa.rb
class NoticiaEmpresa < ActiveRecord::Base
  belongs_to :empresa
  has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "300x300>" }
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

   def image_url
     image.url(:thumb)
   end
end

app/models/opinion.rb
class Opinion < ActiveRecord::Base
	belongs_to :item_producto
end

app/models/preparar_mate.rb
class PrepararMate < ActiveRecord::Base
	belongs_to :producto
	
end

app/models/producto.rb
class Producto < ActiveRecord::Base
  belongs_to :empresa
  has_many :item_productos, dependent: :destroy
  has_many :prop_generals, dependent: :destroy
  has_many :galeria_procesos, dependent: :destroy
  has_many :preparar_mates, dependent: :destroy
  has_many :galeria_prep_mates, dependent: :destroy
end

app/models/prop_especifica.rb
class PropEspecifica < ActiveRecord::Base
	belongs_to :detalle
end

app/models/prop_general.rb
class PropGeneral < ActiveRecord::Base
	belongs_to :producto
	has_many :prop_general_items, dependent: :destroy
	has_many :galeria_props, dependent: :destroy
end

app/models/ubicacion_geo.rb
class UbicacionGeo < ActiveRecord::Base
  belongs_to :empresa
  geocoded_by :address
  after_validation :geocode
  
  has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "300x300>" }
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
  def image_url
     image.url(:thumb)
  end

end

app/models/video.rb
class Video < ActiveRecord::Base
	  belongs_to :empresa
      
end

app/models/videos_producto.rb
class VideosProducto < ActiveRecord::Base
	belongs_to :item_producto
end

app/controllers/productos_controller.rb
class ProductosController < ApplicationController


  # GET /productos
  # GET /productos.json
  def index
    @empresa = Empresa.find(params[:empresa_id])
    @productos = @empresa.productos
  end

  # GET /productos/1
  # GET /productos/1.json
  def show
    @empresa = Empresa.find(params[:empresa_id])
    @producto = @empresa.productos.find(params[:id])
  end

  # GET /productos/new
  def new
       @empresa = Empresa.find(params[:empresa_id])
       @producto = @empresa.productos.new
  end

  # GET /productos/1/edit
  def edit
    @empresa = Empresa.find(params[:empresa_id])
    @producto = @empresa.productos.find(params[:id])
  end

  # POST /productos
  # POST /productos.json
  def create
    @empresa = Empresa.find(params[:empresa_id])
    @producto = @empresa.productos.new(producto_params)
    respond_to do |format|
      if @producto.save
        format.html { redirect_to empresa_productos_path, notice: 'Producto was successfully created.' }
        format.json { render :show, status: :created, location: @producto }
      else
        format.html { render :new }
        format.json { render json: @producto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /productos/1
  # PATCH/PUT /productos/1.json
  def update
    @empresa = Empresa.find(params[:empresa_id])
    @producto = @empresa.productos.find(params[:id])
    respond_to do |format|
      if @producto.update(producto_params)
        format.html { redirect_to empresa_productos_path, notice: 'Producto was successfully updated.' }
        format.json { render :show, status: :ok, location: @producto }
      else
        format.html { render :edit }
        format.json { render json: @producto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /productos/1
  # DELETE /productos/1.json
  def destroy
    @empresa = Empresa.find(params[:empresa_id])
    @producto = @empresa.productos.find(params[:id])
    @producto.destroy
    respond_to do |format|
      format.html { redirect_to empresa_productos_path, notice: 'Producto was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.

    # Never trust parameters from the scary internet, only allow the white list through.
    def producto_params
      params.require(:producto).permit(:titulo, :empresa_id)
    end
end

app/helpers/audios_helper.rb
module AudiosHelper
end

app/helpers/detalles_helper.rb
module DetallesHelper
end

app/helpers/productos_helper.rb
module ProductosHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/productos/_form.html.erb
<%= form_for ([@empresa,@producto])  do |f| %>
  <% if @producto.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@producto.errors.count, "error") %> prohibited this producto from being saved:</h2>

      <ul>
      <% @producto.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<form class="form-horizontal" >
  <fieldset>
    <legend>Datos de Categoria del Producto</legend>
     <div class="form-group">
      <label for="" class="col-lg-2 control-label">Titulo:</label>
      <div class="col-lg-10">
        <%= f.text_field :titulo, class: "form-control", placeholder: "Título"%>
      </div>
    </div>
  <div class="col-lg-offset-4">
    <div class="btn-group">
      <a> <%= f.submit "Guardar", class: "btn btn-info btn-raised" %></a>
    </div>
    <div class="btn-group">     
     <a> <%= link_to 'Volver', empresa_productos_path,class: "btn btn-info btn-raised" %></a>
   </div>
  </div>  
<% end %>

app/views/productos/edit.html.erb
<div class="container">
    <div class="row">
        <div class="col-lg-7 col-lg-offset-3">
            <div class="panel panel-info">
                <div class="panel-heading">
                    <h2 class="panel-title text-center">Editar Categoria de Producto</h2>
                </div>
                    
                <div class="panel-body">
    				<%= render 'form' %>
    			</div>
    		</div>
    	</div>
    </div>
</div>

app/views/productos/index.html.erb
<div class="container">
    <div class="row">
        <div class="col-md-8 col-lg-offset-2">
            <div class="panel panel-info">
                <div class="panel-heading">
                    <h2 class="panel-title text-center" >Categoria de Productos</h2>
                </div>
                <div class="col-lg-offset-5">
                    <div class="btn-group">
                        <a ><%= link_to "<button type='button'class='btn btn-info'>Nuevo</button>".html_safe, new_empresa_producto_path%></a> 
                    </div>
                    <div class="btn-group">    
                        <a ><%= link_to "<button type='button'class='btn btn-info'>Volver</button>".html_safe, empresa_path(@empresa)%></a>   
                    </div>
                </div>
                <div class="panel-body">
                    <table class="table table-striped"> 
                        <thead>                              
                            <tr class="info">
                              <th class="text-center">Categoria del Producto</th>
                              <th class="text-center">Acciones</th>
                            </tr>
                      </thead>
                     <% if @empresa.productos.empty? == false%>
                        <% @productos.each do |producto| %>
                            <div class="row">
                              <tr class="active">
                                <td><h6><%= producto.titulo %></h6></td>
                                <td>
                                    <div class="col-lg-offset-2">
                                      <div class="btn-group">
                                            <a><%= link_to 'Productos', empresa_producto_path(@empresa,producto), :class => "btn btn-info btn-raised"%></a>
                                            <a><%= link_to 'Editar', edit_empresa_producto_path(@empresa,producto) ,:class => "btn btn-info btn-raised"%></a>
                                            <a><%= link_to 'Eliminar',[producto.empresa, producto], method: :delete, data: { confirm: 'Are you sure?' },:class => "btn btn-info btn-raised" %></a>
                                        </div>
                                      </div>
                                </td>
                              </tr>
                            </div>
                        <% end %>
                    <% end %>
                </table>  
              </div>
            </div>
        </div>
    </div>
</div>

app/views/productos/new.html.erb
<div class="container">
    <div class="row">
        <div class="col-lg-7 col-lg-offset-3">
            <div class="panel panel-info">
                <div class="panel-heading">
                    <h2 class="panel-title text-center">Nueva Categoria de Producto</h2>
                </div>
                    
                <div class="panel-body">
    				<%= render 'form' %>
    			</div>
    		</div>
    	</div>
    </div>
</div>

app/views/productos/show.html.erb
<div class="container">
    <div class="col-lg-8 col-lg-offset-2">
        <div class="panel panel-info">
            <div class="panel-heading">
                <h2 class="panel-title text-center">Gestión de Categoria del Producto</h2>
            </div>

            <div class="panel-body">
                <form class="form-horizontal" >
                 <legend>Datos de Categoria</legend>
                 <fieldset>
                    <div class="form-group">
                        <label for="" class="col-lg-2 control-label">Nombre:</label>
                        <%=text_field_tag 'query',@producto.titulo ,:readonly => true%>
                    </div>                                
                </fieldset>
            </form>  
        </div> 
    </div>
    <div class="panel panel-info">
        <div class="panel-body text-center">
            <div class="btn-group-vertical">
                <a href="javascript:void(0)" ><%= link_to 'Información de productos', empresa_producto_item_productos_path(@empresa,@producto),:class => "btn btn-info btn-raised" %></a>
                <a href="javascript:void(0)" ><%= link_to 'Propiedades',  empresa_producto_prop_generals_path(@empresa,@producto) ,:class => "btn btn-info btn-raised" %></a>
                <a href="javascript:void(0)" ><%=link_to 'Preparación para el consumo',  empresa_producto_galeria_prep_mates_path(@empresa,@producto),:class => "btn btn-info btn-raised" %></a>
            </div>
            <div class="btn-group-vertical">
                <a href="javascript:void(0)" ><%= link_to 'Procesos de elaboración',  empresa_producto_galeria_procesos_path(@empresa,@producto) ,:class => "btn btn-info btn-raised" %></a>        
                <a href="javascript:void(0)" ><%= link_to 'Tips para el consumo',  empresa_producto_preparar_mates_path(@empresa,@producto),:class => "btn btn-info btn-raised" %></a>
                <a href="javascript:void(0)" ><%=link_to 'Volver',  empresa_productos_path,:class => "btn btn-info btn-raised" %></a>                     
                
            </div>

        </div>
    </div>
</div>
</div>