config/routes.rb
Rails.application.routes.draw do
  
resources :audios
root :to => "empresas#index"
resources :empresas do
  resources :ubicacion_geos do
    collection do
        get 'mapComplet'
    end
  end
  resources :estadisticas
  resources :noticia_empresas
  resources :videos
  resources :consulta_clientes
  resources :productos do
    resources :galeria_procesos
    resources :preparar_mates
    resources :galeria_prep_mates
    resources :prop_generals do
      resources :prop_general_items
      resources :galeria_props
    end
    resources :item_productos do
       resources :galeria_imagenes
       resources :videos_productos
       resources :opinions
       resources :detalles do
          resources :prop_especificas
       end
    end
  end
  resources :informacion_empresas do
    resources :item_de_infos
  end
end

end

app/models/galeria_imagene.rb
class GaleriaImagene < ActiveRecord::Base
  belongs_to :item_producto
  has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "300x300>" }
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

   def image_url
     image.url(:thumb)
   end
end

app/controllers/galeria_imagenes_controller.rb
class GaleriaImagenesController < ApplicationController
  # GET /galeria_imagenes
  # GET /galeria_imagenes.json
  def index
    @empresa = Empresa.find(params[:empresa_id])   
    @producto = @empresa.productos.find(params[:producto_id])
    @item_producto = @producto.item_productos.find(params[:item_producto_id])
    @galeria_imagenes = @item_producto.galeria_imagenes
    ##respond_to do |format|
    ##  format.html # show.html.erb
    ##  format.json { render :json => @galeria_imagenes }
    ##end
  end

  # GET /galeria_imagenes/1
  # GET /galeria_imagenes/1.json
  def show
    @empresa = Empresa.find(params[:empresa_id])   
    @producto = @empresa.productos.find(params[:producto_id])
    @item_producto = @producto.item_productos.find(params[:item_producto_id])
    @galeria_imagene = @item_producto.galeria_imagenes.find(params[:id])
  end

  # GET /galeria_imagenes/new
  def new
    @empresa = Empresa.find(params[:empresa_id])   
    @producto = @empresa.productos.find(params[:producto_id])
    @item_producto = @producto.item_productos.find(params[:item_producto_id])
    @galeria_imagene = @item_producto.galeria_imagenes.new
  end

  # GET /galeria_imagenes/1/edit
  def edit
    @empresa = Empresa.find(params[:empresa_id])   
    @producto = @empresa.productos.find(params[:producto_id])
    @item_producto = @producto.item_productos.find(params[:item_producto_id])
    @galeria_imagene = @item_producto.galeria_imagenes.find(params[:id])    
  end

  # POST /galeria_imagenes
  # POST /galeria_imagenes.json
  def create
    @empresa = Empresa.find(params[:empresa_id])   
    @producto = @empresa.productos.find(params[:producto_id])
    @item_producto = @producto.item_productos.find(params[:item_producto_id])
    @galeria_imagene = @item_producto.galeria_imagenes.create(galeria_imagene_params)
    respond_to do |format|
      if @galeria_imagene.save
        format.html { redirect_to empresa_producto_item_producto_galeria_imagenes_path, notice: 'Item producto was successfully created.' }
        format.json { render :show, status: :created, location: @galeria_imagene }
      else
        format.html { render :new }
        format.json { render json: @galeria_imagene.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /galeria_imagenes/1
  # PATCH/PUT /galeria_imagenes/1.json
  def update
    @empresa = Empresa.find(params[:empresa_id])   
    @producto = @empresa.productos.find(params[:producto_id])
    @item_producto = @producto.item_productos.find(params[:item_producto_id])
    @galeria_imagene = @item_producto.galeria_imagenes.find(params[:id])
    respond_to do |format|
      if @galeria_imagene.update(galeria_imagene_params)
        format.html { redirect_to empresa_producto_item_producto_galeria_imagenes_path, notice: 'Item producto was successfully updated.' }
        format.json { render :show, status: :ok, location: @galeria_imagene }
      else
        format.html { render :edit }
        format.json { render json: @galeria_imagene.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /galeria_imagenes/1
  # DELETE /galeria_imagenes/1.json
  def destroy
    @empresa = Empresa.find(params[:empresa_id])   
    @producto = @empresa.productos.find(params[:producto_id])
    @item_producto = @producto.item_productos.find(params[:item_producto_id])
    @galeria_imagene = @item_producto.galeria_imagenes.find(params[:id])
    @galeria_imagene.destroy
    respond_to do |format|
      format.html { redirect_to empresa_producto_item_producto_galeria_imagenes_path, notice: 'Item producto was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.


    # Never trust parameters from the scary internet, only allow the white list through.
    def galeria_imagene_params
      params.require(:galeria_imagene).permit(:titulo, :descripcion, :image)
    end
end

app/views/galeria_imagenes/_form.html.erb
<%= form_for([@empresa,@producto,@item_producto,@galeria_imagene]) do |f| %>
<% if @galeria_imagene.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@galeria_imagene.errors.count, "error") %> prohibited this item_producto from being saved:</h2>

  <ul>
    <% @galeria_imagene.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>
<form class="form-horizontal" >
  <fieldset>
  <legend>Datos de la Imagen </legend>
    <div class="form-group">
      <label for="" class="col-lg-2 control-label">Título:</label>
      <div class="col-lg-10">
        <%= f.text_field :titulo, class: "form-control", placeholder: "Título"%>
      </div>
    </div>
    <div class="form-group">
      <label for="" class="col-lg-2 control-label">Descripción:</label>
      <div class="col-lg-10">
        <%= f.text_area :descripcion, class: "form-control", placeholder: "Descripción"%>
      </div>
    </div>
    <div class="form-group">
      <label for="" class="col-lg-2 control-label">Descripción:</label>
      <div class="col-lg-10">
        <%= f.file_field :image, class: "form-control"%>
      </div>
    </div>
    <div class="col-lg-offset-4">
      <div class="btn-group">
       <a><%= f.submit "Guardar", class: "btn btn-info btn-raised" %></a>  
     </div>
     <div class="btn-group">     
       <a><%= link_to "Volver", empresa_producto_item_producto_galeria_imagenes_path,class: "btn btn-info btn-raised" %></a>  
     </div>
   </div>
 </fieldset>
</form>

<% end %>

app/views/galeria_imagenes/edit.html.erb
<div class="container">
	<div class="row">
	    <div class="col-lg-7 col-lg-offset-2">
	        <div class="panel panel-info">
	            <div class="panel-heading">
	                <h2 class="panel-title text-center">Editar Datos de Imagen para la Galeria de Imagenes</h2>
	            </div>
	                
	            <div class="panel-body">
					<%= render 'form' %>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/galeria_imagenes/index.html.erb
<div class="container">
<div class="col-md-8 col-lg-offset-2">
  <div class="row">
    <div class="panel panel-info">
      <div class="panel-heading">
        <h2 class="panel-title text-center" >Galeria de Imagenes del Producto</h2>
      </div>   
      <div class="col-lg-offset-5">
        <div class="btn-group">
          <a ><%= link_to "<button type='button'class='btn btn-info'>Nuevo</button>".html_safe, new_empresa_producto_item_producto_galeria_imagene_path  %></a> 
        </div>
        <div class="btn-group">
          <a ><%= link_to "<button type='button'class='btn btn-info'>Volver</button>".html_safe, empresa_producto_item_productos_path %></a>  
        </div>
      </div>            
          <% if @item_producto.galeria_imagenes.empty? == false%>
      <div class="panel-body">
        <table class="table table-striped "> 
          <thead>
            <tr class="info">
             <th class="text-center"><h5><b>Título</b></h5></th>
             <th class="text-center"><h5><b>Descripción</b></h5></th>
             <th class="text-center"><h5><b>Imagen</b></h5></th>
             <th class="text-center"><h5><b>Acciones</b></h5></th>
           </tr>
         </thead>
         <tbody>
          <% @galeria_imagenes.each do |galeria_imagene| %>
          <div class="row">
            <tr class="active">
              <td><h5><%= galeria_imagene.titulo %></h5></td>
              <td class="col-md-3"><h5><%= galeria_imagene.descripcion%></h5></td>
              <td class="text-center"><h5><%= image_tag galeria_imagene.image.url(:thumb) %></h5></td>
              <td class="text-center">
                <div class="btn-group btn-group-vertical">
                  <!--<a><%= link_to 'Show',   empresa_producto_item_producto_galeria_imagene_path(@empresa,@producto,@item_producto,galeria_imagene), :class => "btn btn-info" %></a>-->
                  <a><%= link_to 'Editar', [:edit, @empresa,@producto,@item_producto,galeria_imagene], :class => "btn btn-info"%></a>     
                  <a><%= link_to 'Eliminar',empresa_producto_item_producto_galeria_imagene_path(@empresa,@producto,@item_producto,galeria_imagene), method: :delete, data: { confirm: 'Are you sure?' },:class => "btn btn-info" %></a> 
                </div>
              </td>
            </tr>
          </div>
          <% end %>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>
</div>
</div>

app/views/galeria_imagenes/new.html.erb
<div class="container">
	<div class="row">
	    <div class="col-lg-7 col-lg-offset-2">
	        <div class="panel panel-info">
	            <div class="panel-heading">
	                <h2 class="panel-title text-center">Nueva Imagen para la Galeria de Imagenes</h2>
	            </div>
	                
	            <div class="panel-body">
					<%= render 'form' %>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/galeria_imagenes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Titulo:</strong>
  <%= @galeria_imagene.titulo %>
</p>

<p>
  <strong>Descripcion:</strong>
  <%= @galeria_imagene.descripcion %>
</p>

<p>
  <strong>Imagen:</strong>
  <td><%= image_tag @galeria_imagene.image.url(:thumb) %></td>
</p>

<%= link_to 'Edit', edit_empresa_producto_item_producto_galeria_imagene_path(@empresa,@producto,@item_producto,@galeria_imagene) %> 
<%= link_to 'Back',  empresa_producto_item_producto_galeria_imagenes_path %>